# Generated by Django 5.0.1 on 2024-02-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.CharField(default='', max_length=50)),
                ('orderdate', models.DateField(null=True)),
                ('deliverydate', models.DateField(null=True)),
                ('deliverytype', models.CharField(default='', max_length=50)),
                ('userid', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('segment', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('upcity', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('area', models.CharField(default='', max_length=50)),
                ('productid', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('categorydetail', models.CharField(default='', max_length=50)),
                ('productname', models.CharField(default='', max_length=50)),
                ('sales', models.FloatField(default='', null=True)),
                ('quantity', models.IntegerField(default='')),
                ('discountrate', models.FloatField(default='', null=True)),
                ('revenue', models.FloatField(default='')),
            ],
        ),
    ]
