# Generated by Django 5.0.1 on 2024-02-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='categorydetail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='productname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
